# Generated by Django 5.2.7 on 2025-11-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/1377010.jpg', upload_to='profile_images'),
        ),
    ]
